server:
  port: 8090

spring:
  data:
    mongodb:
      username: user
      password: password
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin


