server:
  port: 8040

spring:
  data:
    mongodb:
      username: user
      password: password
      host: localhost
      port: 27017
      database: notification
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.ecommerce.orderservice.producer.entities.OrderConfirmation,paymentConfirmation:com.ecommerce.paymentservice.producer.entities.PaymentNotificationRequest
  mail:
    host: localhost
    port: 1025
    username: user
    properties:
      mail:
        smtp:
           trust: "*"
        auth: true
        starttls:
          enabled: true
        timeout: 3000
        writetimeout: 5000
        connectiontimeout: 5000


